### ISSUE TITLE
Add timestamps in the exported gpx tracks.

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#604] opened 2022-08-17 08:49 UTC
It is recommended to add "virtual" generated time stamps into the export track trackpoints that do correspond to the expected travel speed and are intended for valuable ETA predictions and ETA display and by that it is very useful information.
Or must be published into ?
[abrensch](https://github.com/abrensch)
/
[brouter](https://github.com/abrensch/brouter)

**Comment by janusbenissa** [comment] 2022-08-17 11:00
And how do you expect to calculate the expected travel speed??

**Comment by 0709wiwiwi** [comment] 2022-08-17 13:40
BRouter web already exports the necessary info in the osmand format.
The (rte) route contains the <time> offset in seconds between instructions. 
The time offset varies according to the selected profile. Trekking, Fast bike, Car.

The positions of the route points correspond to identically positioned track points. 
I start the track time example at zero hour UTC and then add the timestamps. 
Missing trackpoint timestamps are than attached by the gps track editor.

In attachment an example from BRouter web dowload to final result.
The example here was a design through the selected profile Car (fast).

I expect this can so already be exported in a  simple way by the Brouter.
[Brouter(web) timestamps completed.zip.txt](https://github.com/nrenner/brouter-web/files/9363142/Brouter.web.timestamps.completed.zip.txt)

**Comment by janusbenissa** [comment] 2022-08-17 13:50
The times Brouter uses are for me totally useless, the count for a hike 4kmh, while in real  I do 2kmh or less on a difficult route.

**Comment by 0709wiwiwi** [comment] 2022-08-17 15:00
So you knew it could be done? Useless? That's a strong word for a free service.  Even if you know in advance that you are only half as fast.  Perhaps you can come up with a suggestion for improvement based on your own finely tuned profile ? You can probably be helped by other users who specialise in such profile development.  Seriously.
Personally, I don't expect personalised timings from a general "router service" but I do sure like a hint before I start. Even more decisive is the distance I will cycle as a tourist. How long it takes me to get there, with or without friends, is sometimes determined by quite different factors.
As soon as I start cycling, the app I use adjusts the time indications to my average speed. I am quite happy with that.

**Comment by janusbenissa** [comment] 2022-08-17 15:13
I use the web based version and don't look to the times and I don't blame the makers that the times are wrong. I understand that it is nearly impossible the get the correct times.
Doing a hike or bike ride on a flat asphalt road is totally different than a hike or bike ride on a steep hill where your have to search between the bushes if you have the correct route.

**Comment by 0709wiwiwi** [comment] 2022-08-17 15:29
Yes, that is correct. I am mainly active on flat terrain and only as a touring cyclist. The (head) wind is therefore usually a more decisive factor for the speed. 
I once thought of a proposal to do something like that IN THE APP itself, but it might be worthless in the end.  Not tried.
You can find it here in reply #2. https://forum.locusmap.eu/index.php?topic=5953.msg49935#msg49935
I had one (PM) comment from a hiker who said that the speed when descending is slower than on the flat, just like when ascending. If you take a look at the image you could also fit this in perfectly I thought, so the speed top can also be onto the flat part.

**Comment by nrenner** [comment] 2022-08-17 16:22
Closing as duplicate of #196. You can vote for that feature request by adding a thumbs-up there (smiley button top right).

Estimated speed calculation is done in brouter [StdPath.computeKinematic](https://github.com/abrensch/brouter/blob/70c0e7ca3ebcd125b9c94ed2fa842745580525a9/brouter-core/src/main/java/btools/router/StdPath.java#L230-L276), see also [brouter#6](https://github.com/abrensch/brouter/issues/6). It does take elevation into account, but not road/path conditions or difficulty.

**Comment by nrenner** [comment] 2022-08-17 16:22
Duplicate of #196

**Closed by nrenner** 2022-08-17 16:22 UTC
