### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by VoyteckPL** [nrenner/brouter-web#122] opened 2018-05-19 09:51 UTC
I get this error when trying to draw any route using http://brouter.damsy.net

**Comment by bagage** [comment] 2018-05-20 08:14
Hey @VoyteckPL, could you past an example URL where you get this error? It seems to me that it does not happen 100% of the time and I cannot find an example right now. 
I'll look into it, thanks!

**Comment by VoyteckPL** [comment] 2018-05-20 08:30
http://brouter.damsy.net/latest/#map=15/54.4982/18.4783/OpenStreetMap&lonlats=18.488656,54.498613|18.475182,54.499958

I have added a custom overlay. May that be a reason? I guess not.

**Comment by bagage** [comment] 2018-05-20 08:31
Thanks, I can reproduce it with your link too. I'll investigate, thanks :).

**Comment by VoyteckPL** [comment] 2018-05-20 08:33
Perfect. By the way, this "damsy" version looks great. I love the option to add my own maps!

https://s9.postimg.cc/4qd9d1k6n/Przechwytywanie.png

**Comment by VoyteckPL** [comment] 2018-05-20 08:35
Oh I forgot, I'm also unable to delete custom overlay once I add it.

**Comment by bagage** [comment] 2018-05-21 11:38
> Oh I forgot, I'm also unable to delete custom overlay once I add it.

Hm? It seems to work fine here, see this small recording: http://webm.land/w/FDQ6/

Regarding the bug, I cannot reproduce it again with your link so I cold not find a solution yet. Still investigating.

**Comment by bagage** [comment] 2018-05-21 20:52
I've tried something - please let me know if the problem is still there (with broken URLs please).

**Comment by bagage** [comment] 2018-05-23 18:22
Can you try changing the profile and see if it fixes the problem?

**Comment by VoyteckPL** [comment] 2018-05-23 19:27
I tried, every profile...Doesn't work :(

**Comment by bagage** [comment] 2018-05-23 19:32
Can you open the developer console (right click -> examine), and paste logs here please? On my side (where it works OK), I can see:

```
Profile trekking is not available in cache, trying to download it…
brouter-web.js:63:753
Downloading profile from https://brouter.damsy.net/profiles/trekking.brf
brouter-web.js:63:1316
No need to download profile, none is set yet
```

Please gather all logs for the following sequence:

1. Open [your route](http://brouter.damsy.net/latest/#map=15/54.4982/18.4783/OpenStreetMap&lonlats=18.488656,54.498613%7C18.475182,54.499958) in a tab
2. Select another profile (let's say "Shortest")
3. Come back to "Trekking" profile

It might give us a clue :). Thanks!

**Comment by VoyteckPL** [comment] 2018-05-23 19:38
Step 1:
Profile.js:36 Profile trekking is not available in cache, trying to download it…
Downloading profile from https://brouter.damsy.net/profiles/trekking.brf
Profile.js:85 No need to download profile, none is set yet
/latest/#map=15/54.4982/18.4783/OpenStreetMap&lonlats=18.488656,54.498613%7C18.475182,54.499958:1 Failed to load https://brouter.damsy.net/api/brouter?lonlats=18.488656,54.498613|18.475182,54.499958&profile=trekking&alternativeidx=0&format=geojson: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://brouter.damsy.net' is therefore not allowed access.

Step 2:

Profile.js:36 Profile shortest is not available in cache, trying to download it…
Profile.js:58 Downloading profile from https://brouter.damsy.net/profiles/shortest.brf
/latest/#map=15/54.4982/18.4783/OpenStreetMap&lonlats=18.488656,54.498613|18.475182,54.499958&profile=shortest:1 Failed to load https://brouter.damsy.net/api/brouter?lonlats=18.488656,54.498613|18.475182,54.499958&profile=shortest&alternativeidx=0&format=geojson: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://brouter.damsy.net' is therefore not allowed access.
Step 3:

Profile.js:79 Profile trekking found in cache, using it
/latest/#map=15/54.4982/18.4783/OpenStreetMap&lonlats=18.488656,54.498613|18.475182,54.499958:1 Failed to load https://brouter.damsy.net/api/brouter?lonlats=18.488656,54.498613|18.475182,54.499958&profile=trekking&alternativeidx=0&format=geojson: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://brouter.damsy.net' is therefore not allowed access.

**Comment by bagage** [comment] 2018-05-23 19:46
Duh, thanks for the log! I believe you are using http (and not https), and indeed this is broken on it! I'll fix it.

**Comment by VoyteckPL** [comment] 2018-05-23 19:48
ohhh I checked with https and it works.... What an easy mistake !

**Comment by bagage** [comment] 2018-05-23 20:27
The problem should be definitely fixed now. Thanks for your help @VoyteckPL!

**Closed by bagage** 2018-05-23 20:27 UTC

**Comment by VoyteckPL** [comment] 2018-05-24 03:48
Thanks!
