### ISSUE TITLE
[suggestion] Show grade

### ISSUE THREAD

**Issue by Shohreh** [nrenner/brouter-web#351] opened 2020-12-03 22:57 UTC
Hello,

I suggest showing how steep a road is:

![https://i.postimg.cc/KvY2mTfP/image.png](https://i.postimg.cc/KvY2mTfP/image.png)

Cheers,

**Comment by nrenner** [comment] 2020-12-04 08:22
Closing as duplicate of #55.

Coloring by grade is on its way in #343 / #345, it doesn't show the exact grade though.

**Closed by nrenner** 2020-12-04 08:22 UTC
