### ISSUE TITLE
yarn watch is failing after first run

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#234] opened 2019-08-19 18:06 UTC
If running `yarn watch`, the code is built once. Then, on first change on a file, the rebuild is done correctly. After this, it seems subsequent builds are not working anymore. Not sure what is happening.

**Comment by Phyks** [comment] 2019-08-20 13:08
Seems that on a different machine (mac instead of linux), it actually works fine :/

**Comment by nrenner** [comment] 2019-08-20 17:13
Maybe gulp has some verbose/debugging output you could turn on?

**Comment by nrenner** [comment] 2019-08-20 18:04
I needed to increase the inotify file watch limit on Ubuntu 18.04 - but I got this explicit error message from Gulp watch (and similar from VS Code):
`Error: ENOSPC: System limit for number of file watchers reached, watch '...'`

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

**Comment by bagage** [comment] 2019-08-20 18:31
I'm trying to get more logs but `gulp -LLLL watch` does not log anything.

But for me, the issue only happens when running gulp via Intellij IDEA - which consumes a lot of memory and also a lot of file watchers, so maybe I'm getting some issue around that (even if I raised the number to `524288`). Still investigating…

**Comment by Phyks** [comment] 2019-09-02 18:00
I could no longer reproduce it today (before your PR). Not sure what was happening. Feel free to close this one if you cannot reproduce either.

**Comment by bagage** [comment] 2019-09-02 21:00
I'll keep going on #222 and if I cannot reproduce it i'll close this one.

**Closed** 2019-10-01 22:02 UTC
Labels: bug
