### ISSUE TITLE
Show planner and turn trackpoints on the map.

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#565] opened 2022-06-22 16:11 UTC
1. When generate instructions is set, display the **snapped to osm roads** planner and turn trackpoints by a little dot on the map.
An example as was generated by the gpx editor by the navigation instructions attached into the gpx track trackpoints sym tag.
Tap a "dot" to display the turninstruction details.

[1_Barel_navtrkpt.htm.txt](https://github.com/nrenner/brouter-web/files/8959437/1_Barel_navtrkpt.htm.txt)

2. Present the generated turnlist inclusive the **Via** planner points in the "foldable" sidepanel.

**Comment by nrenner** [comment] 2022-06-23 18:49
Closing as duplicate of #42.

**Closed by nrenner** 2022-06-23 18:49 UTC

**Comment by 0709wiwiwi** [comment] 2022-06-23 19:44
Hello Norbert.
Sorry I had not noticed that old contribution of Zossebart, yet it remained open for 6 years ?
So to know how to deal with it in the future **or not** is the question. Definitely closed?
Closed because it technically difficult (yet) to realise, or rather prefer not to see or to realise ?
Thank you in advance for a brief explanation.

**Comment by nrenner** [comment] 2022-06-25 10:06
> yet it remained open for 6 years ?

Well,
- we have a long backlog of 112 open issues (and an even longer private todo list)
- low priority for me
- other contributors implement what they want to have, and this obviously wasn't
- specific hold-up here was long thinking about switching to [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine), that might have helped here, but we didn't in the end
- probably most useful for developers and users investigating turn instructions, less for daily use, so not a popular feature

> Definitely closed?

Only closed this one because it's a duplicate.

Ignore the misleading GitHub close status ("closed this as not planned"), there is only the choice between "Close as completed" and "Close as not planned", both inappropriate for duplicates:
![Close issue screenshot](https://docs.github.com/assets/cb-19592/images/help/issues/close-issue-select-reason.png)
[Closing an issue - GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue)

You can vote for #42 by adding a :+1: with the smiley-button top left of the first comment. So we can [sort issues by reactions](https://github.com/nrenner/brouter-web/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) as one way to measure popularity.

Or you can provide a pull request.

**Comment by nrenner** [comment] 2022-06-25 10:20
Duplicate of #42

(test)

**Comment by nrenner** [comment] 2022-06-25 10:21
Duplicate of #42
