### ISSUE TITLE
Add CyclOSM.org map to layer selection

### ISSUE THREAD

**Issue by mapper-of-openstreets** [nrenner/brouter-web#323] opened 2020-07-07 10:48 UTC
It would be great if the map of CyclOSM.org would also be available in the layer selection. I find the map and the overlay map of CyclOSM.org extremely good for cyclists. Furthermore the maps are always up-to-date.

The URLs for the maps are:
CyclOSM:
https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png

CyclOSM Overlay:
https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png

Further information:
https://www.cyclosm.org
https://wiki.openstreetmap.org/wiki/CyclOSM

**Comment by mjaschen** [comment] 2020-07-07 11:59
Please see #290 and #301.

**Comment by nrenner** [comment] 2020-07-07 21:00
Closing as duplicate of #290.

The status is that I'm waiting for further feedback / permission from CyclOSM developers / OpenStreetMap France.

**Closed by nrenner** 2020-07-07 21:00 UTC
