### ISSUE TITLE
Brouter doesn't understand one-way cycleways.

### ISSUE THREAD

**Issue by vectro** [nrenner/brouter-web#124] opened 2018-06-26 14:23 UTC
Brouter doesn't seem to understand ways like [this one](https://www.openstreetmap.org/way/584971528), which have a cycleway only in one direction (in this case, only in the Southbound direction). It is suggesting using this road when traveling North to South, even though it doesn't actually have any cycling facilities at all (and there are other nearby Southbound options that do).

[here](http://h2096617.stratoserver.net:443/brouter?lonlats=-74.039408,40.715452|-74.015858,40.713972&nogos=&profile=custom_1530022627267&alternativeidx=0&format=geojson) is an example route that shows this problem in practice.

**Comment by Phyks** [comment] 2018-11-06 23:10
Hi,

I was looking at your issue and trying to reproduce / find a fix in a custom profile. However, I don't fully understand the problem. First of all, the way you point is close to Central Park whereas the provided example route is between Wall Street and Jersey. I guess this is simply a bad copy / paste for the route example?

> It is suggesting using this road when traveling North to South, even though it doesn't actually have any cycling facilities at all (and there are other nearby Southbound options that do).

Would you have an example of a route provided by BRouter which is not what you expect as well as the actual route you expect? I'm not at all familiar with cycle network in NYC and it's a bit complicated to replicate / fully understand the issue.

Thanks

**Comment by vectro** [comment] 2018-11-07 03:01
Hi Phyks,

If this bug should be reported elsewhere, please point me in the right direction. I apologize for the bad copy-pasted.

Here is an example:

- [The way brouter does it](http://brouter.de/brouter-web/#map=15/40.7985/-73.9513/OpenStreetMap&lonlats=-73.960991,40.801791|-73.973672,40.779388)
- [A better way to do it](http://brouter.de/brouter-web/#map=15/40.7889/-73.9688/OpenStreetMap&lonlats=-73.960991,40.801791|-73.971806,40.787073|-73.973672,40.779388)

Brouter's approach makes sense in the Northbound direction, but not in the Southbound direction; I think that's because of the unique configuration of this Way.

Does that make sense?

Thanks,

Ian

**Comment by Phyks** [comment] 2018-11-07 08:43
Thanks for the quick feedback on this!

> If this bug should be reported elsewhere, please point me in the right direction.

In my opinion, this issue should rather live in [this repo](https://github.com/abrensch/brouter). The reasoning behind it is that "profiles" (basically, instructions on the cost of each segment of way) and routing are both provided by BRouter itself. Brouter-web is just a frontend on top of it, not actually doing any routing-related stuff. So, it's probably fine to have it here (it's already here since June, 26th :) but it's likely to have more views and people interested in this issue are more likely to see it if it's directly in BRouter repo.

Note that this is just my personal opinion, I'm not part of brouter or brouter-web repository (just interested in this issue and trying to solve it).


> Here is an example

Thanks a lot, that's exactly the kind of example I was looking for! Really nice and clear!


> Brouter's approach makes sense in the Northbound direction, but not in the Southbound direction; I think that's because of the unique configuration of this Way.

So, this kind of issue is rather easy to solve and can be solved by tweaking the [profile](https://github.com/abrensch/brouter/blob/master/misc/profiles2/trekking.brf). I worked a bit on the `trekking` profile to improve it, here is a WIP version: https://gist.github.com/Phyks/3ffbd554541ff8525f1dace48fd216f8.

Southbound route is then (grey is the one provided by `trekking` profile, blue is the one provided by my modified profile):
![2018-11-07-093647](https://user-images.githubusercontent.com/3856586/48119912-dd312480-e270-11e8-978d-97b4a4adbda0.png)

Northbound route is (grey for regular `trekking` profile, blue for my modified one):
![2018-11-07-093616](https://user-images.githubusercontent.com/3856586/48119944-f639d580-e270-11e8-9954-cc93209ac61c.png)


As a side note, I started maintaining a list of simple examples of particular routes (such as this one) and what Brouter should do, to help debug and improve profiles. This test case has then been added to https://github.com/Phyks/BrouterTesting.

**Comment by vectro** [comment] 2018-11-10 10:59
Thanks Phyks. Have you considered submitting the modified profile as a patch to https://github.com/abrensch/brouter/blob/master/misc/profiles2/trekking.brf ?

**Comment by Phyks** [comment] 2018-11-11 00:02
@vectro  Sure, the PR is [here](https://github.com/abrensch/brouter/pull/123) as well as (I hope) enough details about my modifications :)

**Comment by bagage** [comment] 2019-05-09 08:23
Closing this issue as it is more related to brouter engine, hopefully @Phyks will be merged and the issue fixed!

**Closed by bagage** 2019-05-09 08:23 UTC
