### ISSUE TITLE
Error: from-position not mapped in existing datafile

### ISSUE THREAD

**Issue by panteo** [nrenner/brouter-web#125] opened 2018-08-05 20:26 UTC
Problems with http://brouter.de/brouter-web/ 
It keeps showing "Error: from-position not mapped in existing datafile"

Chrome on Ubuntu 18.04.

**Comment by zackenundpunkte** [comment] 2018-08-05 22:15
I have the same problem in the "rails only" mode. "Trekking" and others work fine.
Current Firefox and Chrome versions on MacOS 10.12.6

**Comment by nrenner** [comment] 2018-08-06 07:27
Thanks for reporting. Closing as duplicate of #126.

**Closed by nrenner** 2018-08-06 07:27 UTC

**Comment by Twisterrrrr** [comment] 2020-01-07 16:02
same problem in "River mode"
Chrome and Opera on Windows 10 x64

**Comment by nrenner** [comment] 2020-01-07 17:06
Works for me, so no general problem.

Can you please create a new issue for the backend brouter repo:
https://github.com/abrensch/brouter/issues/new
and post your URL from the browser address bar.
