### ISSUE TITLE
Feature Request: Loading config files from urls

### ISSUE THREAD

**Issue by pedrorolo** [nrenner/brouter-web#149] opened 2019-01-20 12:03 UTC
It would be cool if one could enter the url of a config file instead of the whole file content.

**Comment by poutnikl** [comment] 2019-01-20 13:11
You may mean a custom profile...

I guess it may have been already requested.

**Comment by nrenner** [comment] 2019-01-24 18:02
A planned feature is an option to store a profile permanently and to add a reference to the URL.

Closing as duplicate of #26.

**Closed by nrenner** 2019-01-24 18:02 UTC
