### ISSUE TITLE
Change the color of a loaded GPX track (which can only be blue as of today)

### ISSUE THREAD

**Issue by robobobeng** [nrenner/brouter-web#377] opened 2021-02-27 16:38 UTC
Hi, everything is in the title of the issue: it would be nice to be able to change the color of a GPX track you loaded in BRouter-web. Indeed, when you load a track it is shown as a thick blue line. It is impossible (or I haven't found out how to yet) to change the color and/or the thickness of this line.

Same goes when you load several GPX tracks at the same time : they all show up as blue thick lines. Being able to change the colors would help a lot telling one track from another.

Pictured below: a bunch of tracks, all of them are blue... hard to sort it out!
![image](https://user-images.githubusercontent.com/41967635/109393542-aa6c3800-7922-11eb-8dfb-43164d583dd8.png)

**Comment by nrenner** [comment] 2021-03-01 19:24
Closing as duplicate of #297.

**Closed by nrenner** 2021-03-01 19:24 UTC
Labels: enhancement
