### ISSUE TITLE
Unable to build (bower install)

### ISSUE THREAD

**Issue by giggls** [nrenner/brouter-web#98] opened 2017-11-14 11:55 UTC
Hello,

when doing bower install (bower Version 1.8.2) I get the following:
 brouter-web/ > bower install
bower invalid-meta  for:/home/brouter/brouter-web/bower.json
bower invalid-meta  The "main" field cannot contain globs (example: "*.js")
bower extra-resolution      Unnecessary resolution: leaflet.elevation#master

**Comment by nrenner** [comment] 2017-11-14 12:35
Will look into it later, but removing the line
```
"main": "dist/**/*",
```
from the `bower.json` file should help for now.

**Comment by giggls** [comment] 2017-11-14 13:09
Builds, and mostly works.

One more issue:
Looks like image path is missing the trailing slash:
My browser is trying to open files like these:
http://.../brouter-web/dist/imagesmarker-icon.png which should obviously be
http://.../brouter-web/dist/images/marker-icon.png

**Comment by nrenner** [comment] 2017-11-14 21:05
Hm, can't reproduce the marker issue and can't really make sense of it, because the icon loading is done by Leaflet itself.

Does this also occur if you download the latest archive, e.g. [0.6.3.zip](https://github.com/nrenner/brouter-web/archive/0.6.3.zip), unpack, and just double-click on the `index.html` without building and thus using the pre-built `dist` files? 

What download file have you used and which Browser are you using?

**Comment by bagage** [comment] 2017-11-15 08:13
I had this issue at a time too, though I cannot remember right now the fix… I'll try to remember, sorry for the non-help!

**Comment by giggls** [comment] 2017-11-15 09:16
* unzip 0.6.3.zip
* customize config.js and keys.js

-> Everything works fine.

`npm install`
`bower install`
-> Stil fine.

`gulp`
-> Image links broken

**Comment by nrenner** [comment] 2017-11-15 10:02
`bower install` asked me to choose a Leaflet version, because an updated dependency references a newer version. It might be a Leaflet version issue, for brouter-web 0.6.3 it should be 0.7.7, not 1.0.3.

Can you please check the Leaflet version by pasting/typing 
```
L.version
``` 
into the Browser Console.

**Comment by giggls** [comment] 2017-11-15 10:12
Jepp I chose the newest one. Going back to  0.7.7 solved the problem for me. For some unknown reason my other problem has now gone as well.

**Comment by nrenner** [comment] 2017-11-15 10:48
Good to hear and sorry for the inconvenience. These issues are fixed on master, but the stable release should be updated as well, will therefore leave this issue open.

**Closed** 2018-01-29 18:32 UTC
