### ISSUE TITLE
enforce https as default

### ISSUE THREAD

**Issue by lucamp** [nrenner/brouter-web#546] opened 2022-05-20 09:58 UTC
# steps
- open firefox
- go to "brouter.de" (or "brouter.de/brouter-web) omitting http protocol

# description
sites are opened with http only, even if https protocol is available.
The only option to have automatic redirect is to enable https only in firefox' setting or installing https everywhere extensions; however both can cause issues with sites where https in not fully available (sure, it's not brouter fault)

Is there a way to make https as a default on your side without modification?

Https will be useful when using a custom layer with a personal API key, and for more privacy of course

Thanks
Luca

**Comment by nrenner** [comment] 2022-05-20 14:09
Closing as duplicate of abrensch/brouter#311

**Closed by nrenner** 2022-05-20 14:09 UTC
