### ISSUE TITLE
disable routing between points (manually drawing of paths)

### ISSUE THREAD

**Issue by techtimo** [nrenner/brouter-web#380] opened 2021-03-04 08:12 UTC
Hi there,

this is a feature request.
I just recently started mapping with the help of the Strava Heatmap. Often the paths are too small to put upload them to OSM, but still they are really great, to see where people have went.

If I use the hiking profile I would love to have a option to manually draw direct lines (ontop of what I can see with the strava heat map). I don't have a good option in mind on how this could look like though.
Because changing the profile reroutes the complete drawn path, not only the last segment.

**Comment by mjaschen** [comment] 2021-03-04 08:18
Duplicate of #68

**Comment by bagage** [comment] 2021-03-04 11:22
Indeed, you can upvote #68 if you wish!

**Closed by bagage** 2021-03-04 11:22 UTC
