### ISSUE TITLE
Mobile web client - compatible mobile browsers

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#82] opened 2017-05-04 11:40 UTC
What mobile browsers are tested or aimed to be compatible ?

E.g. , on android 4.3, resolution 852*480 / Sony Xperia M Dual
Firefox is compatible, Chrome I guess is compatible ( not using )
Opera mini as representant of data saving browsers is not compatible
CM Browser as a representant of lightweight browsers is not compatible,

The latter 2 do not display  a map.

**Comment by bagage** [comment] 2017-05-04 12:28
It should be compatible with most of browsers ideally (except outdated 
and "bad" ones like IE).
But it might not work for various reasons (settings customization as 
"Do not track"/"Do not save cookies", etc.) - and since we lack of 
testers, we are not aware of issues. I'll insteall Opera and CM 
browser, thanks for reporting these. It might end up with "WONTFIX" but 
we'll see :).

Le jeu. 4 mai 2017 à 13:40, Poutnik <notifications@github.com> a 
écrit :

**Comment by bagage** [comment] 2017-05-05 10:08
I fixed the problem for Safari and CM Browser (I think it's its name). Closing as resolved, please reopen if you still have trouble with one or several browsers :).

**Comment by poutnikl** [comment] 2017-05-05 11:42
The Opera mini,  on wifi and the data saving set to automatic, does display the map.
But statically, as it seems as there is no possible interaction with the map, aside of scroling its static picture.
One is unable to freely slide the map, or let it focus on  searched city, or zoom it in.
Note that Opera Mini is quite wide spread browser on android devices.

**Comment by bagage** [comment] 2017-05-05 12:41
I am not sure how to fix Opera with compression/optimization set to "Extreme". The problem is the same with any leaflet map (see [this demo](leafletjs.com/examples/mobile/example.html) for instance) since Opera catch fingers moves. But settings compression to "High" instead of "Extreme" solves the problem for me, even if suboptimal.

**Comment by bagage** [comment] 2018-01-31 20:33
Since we cannot do much about that, I'll close it for now.

**Closed by bagage** 2018-01-31 20:33 UTC
