### ISSUE TITLE
Custom WMS layers doesn't work 

### ISSUE THREAD

**Issue by kszwaba** [nrenner/brouter-web#714] opened 2023-03-13 11:27 UTC
On
http://brouter.de/brouter-web
I tried to add my own wms layers from
https://geoportal.gov.pl/uslugi/usluga-przegladania-wms
eg.:
https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/HighResolution
https://mapy.geoportal.gov.pl/wss/service/img/guest/TOPO/MapServer/WMSServer
but none of them has been displayed.
In QGIS I see this layers.
Where could be the problem?

Christopher

**Comment by nrenner** [comment] 2023-03-20 11:37
WMS is not supported yet for custom layers and WMTS only with a compatible tiling scheme and if you can provide a full XYZ url. See also #337.

**Comment by nrenner** [comment] 2023-03-20 11:37
Duplicate of #337

**Closed by nrenner** 2023-03-20 11:37 UTC
