### ISSUE TITLE
Load track as route keeping straight line parts

### ISSUE THREAD

**Issue by ArnoEtxe** [nrenner/brouter-web#610] opened 2022-08-18 06:41 UTC
Hello,
I like very much drawing routes alternating automatic routing and straight lines (vtt and hike).
When i save the file (GPX format with waypoints) and reload it as route (to modify some parts), i lost all the straight line sparts !

Is it possiible to keep this alternance with automatic routing and straight line, as original route ?

Best regards

**Comment by nrenner** [comment] 2022-08-18 08:56
Duplicate of #16

Currently we only export a GPX track (`trk`), that has no information about the route and straight lines and how it was generated. That would require exporting a GPX route (`rte`) with additional information (or using the recently added `link` as a shortcut). This is covered by #16.

**Closed by nrenner** 2022-08-18 08:56 UTC
