### ISSUE TITLE
Don't see cycleway:right=lane?

### ISSUE THREAD

**Issue by GeorgV** [nrenner/brouter-web#325] opened 2020-07-16 16:37 UTC
Please see the difference from the brouter way
http://brouter.de/brouter-web/#map=17/41.82831/-71.37554/standard&lonlats=-71.369376,41.829617;-71.380438,41.829409
to the way on the on the standard OSM site
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=41.8296%2C-71.3694%3B41.8292%2C-71.3809#map=17/41.82920/-71.37520
The tag cycleway:right=lane on the way https://www.openstreetmap.org/way/19351535#map=17/41.82889/-71.37212 (and the following ways seems not to be accepted.

**Comment by EssBee59** [comment] 2020-07-29 13:57
Hello GeorgV,
I never see such OSM object:
highway=motorway AND cycleway:right:lane to  !!!
The problem is not the "right" qualifier but the definition of a "cycleway" on the side (lane) of a motorway...
Are bikers allowed to use such lanes in the USA?
In Europe motorways are NOGO for bikers, so all the biking-profiles forbiddens access to motorways for bikers (with or without lanes)
Regards

**Comment by EssBee59** [comment] 2020-07-29 14:00
PS: if bikers are allowed, you should check the exact status of the highway (motorway or not!)

**Comment by nrenner** [comment] 2020-07-29 20:18
There is already a backend issue for this: abrensch/brouter#63, so closing as duplicate.

**Closed by nrenner** 2020-07-29 20:18 UTC

**Comment by EssBee59** [comment] 2020-07-30 18:16
Hi All,
I think, issue #63 looks like this one, but it is not the same problem:
Here, if you have a look at the OSM object (part of the route on the bridge)
https://www.openstreetmap.org/edit#map=18/41.82920/-71.37520

you wil see these tags:

highway=motorway
bicycle=yes
cycleway:right=lane
etc...
As explained, I think, this combination is NOT valid in Europe.
Bikers are not authorized to use motorways (and lanes of motorways too)
For this reason, all biker-profiles never route bikers on motorways...
 
So I suspect an error in the OSM definition... (truck vs. motorway or something like that)

**Comment by nrenner** [comment] 2020-08-01 14:57
> For this reason, all biker-profiles never route bikers on motorways...

Yes, you're right. With the exception of the `fastbike-asia-pacific` profile, which seems to be specifically made for countries with no such strict rule, see abrensch/brouter#44.

http://brouter.de/brouter-web/#map=17/41.82831/-71.37554/standard&lonlats=-71.369376,41.829617;-71.380438,41.829409&profile=fastbike-asia-pacific

**Comment by EssBee59** [comment] 2020-08-01 15:19
Hello Nrenner,

Thank for the information!
(I am biking only in Europe... it seems very difficult to have profiles with world-wide validity)
So, to this issue:
If motorway for bikers is allowed in the USA GeorgV should use a profile allowing bikers on motorway AND using cycleway:right=lane 

remarks:
- the standard "trekking" do not allow motorway for bikers !!!
- I explained in https://github.com/abrensch/brouter/issues/63 how I am using a lane when it exists only on one side of a highway  (cycleway:right and cycleway:left in combination with reversedirection=yes/no).
