### ISSUE TITLE
brouter-web leaping around, legend is huge

### ISSUE THREAD

**Issue by Tamhlacht** [nrenner/brouter-web#59] opened 2016-12-21 10:55 UTC
Is there an easy video guide to using this router? It's behaving weirdly (on a Mac, in Chrome, with latest MacOS and Chrome version). It won't cancel routes, when i try to size up or down the map it leaps wildly from a street to a country, the 'legend' section on the left has decided to take up half the screen. It's not at all user-friendly.

**Comment by poutnikl** [comment] 2016-12-22 07:50
Can it be related to available web technologies on Mac ? Similar and worse issues are experienced in Android browsers, as BRouter-web functional compatibility with Android browsers is in progress yet.

**Comment by Tamhlacht** [comment] 2016-12-22 09:03
Good point, poutnik; I also have trouble with my country's Ordnance Survey maps, which can be scrolled back to see how the maps looked in 1650 or 1847 or whenever you like. 

But a little more GUI help would be nice. This would be a lovely routing aid for things like my planned cycle across the Esker Riada (the neolithic roads across Ireland on gravel ridges) from Dublin to Galway, if I could get it to work. It would be handy dandy to be able to make a circle of say 10km around my home and then plan a series of cycles radiating out from the centre and save and refine them, if it were a little more user-friendly.

**Comment by Tamhlacht** [comment] 2016-12-22 09:05
And is there any way to make the legend a little more discreet? Damn thing is taking up half my screen! Preferences that could be changed would be nice (well, maybe they're there already & I'm just too stupid to find them.)

![screen shot 2016-12-22 at 09 03 39](https://cloud.githubusercontent.com/assets/24696260/21420454/bc71c7e8-c825-11e6-9cde-6da83ec49f1b.png)

**Comment by Tamhlacht** [comment] 2016-12-22 09:07
And what is this? I know my childhood was a bit all-over-the-place, but gee…! 

![screen shot 2016-12-22 at 09 06 20](https://cloud.githubusercontent.com/assets/24696260/21420494/fdb3dd5e-c825-11e6-9f1d-cd1922c727e4.png)

**Comment by Tamhlacht** [comment] 2016-12-22 09:16
Not to mention this - target island? say what? (The context is that I was experimenting with a cycle route along the cycle-walking path by the river; for some reason Brouter is gulping and spitting at this.)

![screen shot 2016-12-22 at 09 14 44](https://cloud.githubusercontent.com/assets/24696260/21420730/26b87740-c827-11e6-9f26-ad54a6f2b9e8.png)

**Comment by Tamhlacht** [comment] 2016-12-22 09:28
It's also doing something that maddens me in Google Maps - I drag the line, it decides for me that no, the nice riverside cycle lane isn't suitable and I should cycle on the road with the trucks. I drag it again to try to re-educate it. It has now added half a kilometre on to the route. So a route that Strava says is 16.6km is now 18.7km according to Brouter.

**Comment by poutnikl** [comment] 2016-12-22 10:20
To the target island - the destination point is either too far from the OSM routable way network, or at the wa network, but not reachable according to used BRouter profile routing policy.

**Comment by poutnikl** [comment] 2016-12-22 10:25
Routing is not based on neural network learning. It is based on OSM ways data and the BRouter routing profile you use ( standard or custom ). If you are not satified with the route generated for you, you have 3 choices>
- Use different routing profile
- Drag a route toward a way you want to go through, it will ad a viapoint there.
- Modify paramaters of the profiles.
See also [my custom BRouter profiles wiki](https://github.com/poutnikl/Brouter-profiles/wiki)

**Comment by Tamhlacht** [comment] 2016-12-22 10:25
What’s a routable way network?

**Comment by Tamhlacht** [comment] 2016-12-22 10:26
What’s neural network learning? Sorry about this, but I don’t know these
terms.

**Comment by bagage** [comment] 2016-12-22 10:31
> To the target island 
For that, maybe brouter-web could be a bit more userfriendly and displays some generic-error instead. Because basically this errors means "cannot find a way to go from the start to the end", regardless island.

**Comment by poutnikl** [comment] 2016-12-22 10:33
way is any line-like structure in OpenStreetMaps
network is any connections of line-like structures via points called noded.
routable is such a OSM way with tag haigway=*, with meaning generalized road ( from motorways to pedestrian paths ), that is by law and by the profile policy allowed for the vehicle/pedestrian to go through.

So routable way network is connection of all OSM highways that are in current routing mode allowed to use.

**Comment by poutnikl** [comment] 2016-12-22 10:37
neural network learning - forget it - it is not used in context of BRouter engine backend nor BRouter-web fronend GUI. 
( If interested, it is way of human or machine learning by providing example cases in learning phase and then deciding the cases based on what was learned. )

**Comment by Tamhlacht** [comment] 2016-12-22 10:43
Ah, very interesting! So the way babies learn languages!

**Comment by poutnikl** [comment] 2016-12-22 10:45
> Because basically this errors means "cannot find a way to go from the start to the end", regardless island.

In fact not, The target island error is more specific. The other option is a forbidden bottleneck on the road.

**Comment by bagage** [comment] 2016-12-22 10:48
> In fact not, The target island error is more specific. The other option is a forbidden bottleneck on the road.
Yes indeed, I cannot actually reproduce it locally. Could you share (or @Tamhlacht) any url reproducing this issue?

**Comment by poutnikl** [comment] 2016-12-22 10:55
@bagage Not handy. which of them ?
The island one you can achieve in rural areas to place destination far enough from any road/track/path.
The denied bottleneck - the exact error wording I do not remember - try to make BRouter to route you via forbidden way ( e.g. motorway on bike, or a car through path ). eventually cut off via nogo areas all other ways that are usable.

Like schema
<placed nogo circle > - allowed way -<start> - allowed way - not allowed way - allowed way - <destination> - allowed way - <placed nogo circle>

**Comment by Tamhlacht** [comment] 2016-12-22 10:58
Hm. I was trying to get it to route me on my bike along a cycle/walk
riverside path (I’d left it at the default of ‘trekking’).

In another place, the routeer kept refusing to let me drag it onto a
one-way street going the correct way, and instead sending out a spur to
send me up another one-way street the wrong way. (Unless it was sending me
around in a circle between them, not sure.

**Comment by Tamhlacht** [comment] 2016-12-22 10:59
Is there any way to make the big legend take up less space? It’s not
fulfilling any very useful function most of the time, but it’s covering
nearly half of the screen.

**Comment by bagage** [comment] 2016-12-22 11:03
> Is there any way to make the big legend take up less space? It’s not fulfilling any very useful function most of the time, but it’s covering nearly half of the screen. 

#56 is dealing about that yes, but it's not finished yet because none of us are web developers expert unfortunately. For now there is no way to reduce the legend width. But it should not take that much space, only 400px width:

![capture d ecran de 2016-12-22 13-02-08](https://cloud.githubusercontent.com/assets/1451988/21423653/7f2c41b0-c83e-11e6-8d09-a2efa33f28b1.png)

**Comment by Tamhlacht** [comment] 2016-12-22 11:07
Thanks, Gautier - perhaps this is because I’m using a MacBook Air, and the
text, etc is so unfeasibly small on the 13” screen that I tend to cmd+ it
up. I haven’t done this since trying Brouter first, but it may have
remembered the setting.

**Comment by Tamhlacht** [comment] 2016-12-22 11:10
…and yes, I tried cmd-minus and the legend decreased to a normal size.

I’d normally use mouse track pinching to change size in a map, but the
brouter one is a little over-excited in its response, and it tends to leap
to road size and decrease to country size with one pinch.

**Comment by poutnikl** [comment] 2016-12-22 11:10
2 hints - in the bottom right coner one can copy permalink to provide the link to the scenario.
Data link above the left botom text field provided OSM tages for suggested route segments.

**Comment by Tamhlacht** [comment] 2016-12-22 11:11
I thought I saw a way to put a circle of a specific size around a place,
but can’t now see how to do that…?

And is there any way to set ‘directions’ as in Google Maps, by typing in
place names, rather than having to find the destination on the map and
click it?

**Comment by Tamhlacht** [comment] 2016-12-22 11:42
I see (after deploying a microscope) that teenshy text with ‘Permalink’ - I
clicked on it but it didn’t seem to do anything.

Oh, wait, it deployed an information sheet, and froze the page, dammit:

**Comment by poutnikl** [comment] 2016-12-22 12:28
The Black Point icon with a hing  Draw no-go area ( circle ).
The icon with magnifying glass means textual search ( 3rd part online resource ) , either name, either coordinates. the latter is picky, not all coord. formats are accepted.
Permalink serves rather for hoovering over and copying the link to clipboard. then paste to link where you want. Following the link provides BRouter-web with chosen map, region, zoom, start, destination, used(standard) profile + optionally viapoints.

**Comment by Tamhlacht** [comment] 2016-12-22 14:09
Thanks, yes, I tried the magnifying glass; it finds one place but not two
(to be clear, it won’t find Ringsend for me and then find Newcomen Bridge
and offer a route between them, at last I haven’t been able to make it do
so.

The Permalink - you hover and then cmd-c, and what exactly does it paste,
and where would I link it to? Sorry, puzzled by that. Do you mean that once
I’ve worked out how to make a route without it throwing out spurs to here
there and everywhere and sending me all around the world for sport, I can
copy that route into… something… by copy-and-paste? Into what and how?
Google Maps? Apple Maps? TomTom? Word? Here?

It would be nice if Brouter were a downloadable program, because then I
could send you some logs to show how a normally (or perhaps exceptionally)
eejity map user, rather than a geographer or programmer, interacts with the
map.

**Comment by poutnikl** [comment] 2016-12-22 14:19
It uses OSM or other online world-wide place database, so it finds what result is provided.

this link is the state of the BRouter-web screen.  You can share the state of the screens by sharing the link.  After the copy, use it as any other URL link, in the browser address field, or share it as any link anywhere you are used to share links.  

for the route itself, you need to download the GPX files, containing the route.

Brouter IS a downloadable Android program, usable standalone, or as the 3rd party offline routing engine
in Androind GPS applications OSMAnd, LocusMap or OruxMaps.

**Comment by poutnikl** [comment] 2016-12-22 14:21
For the help and discussion, the better place then the issues is the Google group  "osm-android-bikerouting", common for BRouter application and BRouter-web.

**Comment by Tamhlacht** [comment] 2016-12-22 14:22
Even though I don’t use an Android phone or Android tablet?

**Comment by poutnikl** [comment] 2016-12-22 14:32
Even though.  GPX is not Android specific.  Issue discussion are rather for issue or new idea/feature clarifications,  suggestings of workarounds or issue fixes.

**Comment by Tamhlacht** [comment] 2016-12-22 14:33
Thanks; I’ll ask there if I am using the map, then.

**Comment by poutnikl** [comment] 2016-12-22 14:35
what is essential is the very specific features and abilities of BRouter for the bicycle routing, unseen anywhere else. See e.g. https://github.com/poutnikl/Brouter-profiles/wiki

**Comment by Tamhlacht** [comment] 2016-12-22 14:39
Ah, right, excellent!

**Comment by Tamhlacht** [comment] 2016-12-22 14:44
Ah, it’s a Google Group? No, I don’t do Google Groups, they don’t protect
privacy enough for me. That’s a pity.

**Comment by Tamhlacht** [comment] 2016-12-22 14:47
I’ll ask one last question and then leave ye alone: is there any way to
make the pinch to resize the map less sensitive? I find it almost
impossible to control - on Google Maps, for instance, you pinch slowly and
gradually and the map moves slowly and gradually, while on the map used by
Brouter (which may not, of course, be under your control) it leaps from a
50-metre view to a 3km view with one tiny gesture.

**Comment by poutnikl** [comment] 2016-12-22 15:18
I access the Brouter Google group personally via maillist interface only.

If I got it well you ask amout the map zooming in/out.  I have noticed in past that on some machines/browser/mouse(?)/mouse driver(?) combinations, zoomin by the mouse scrolling is too sensitive. In such a case is preferred zooming via zoom in/zo out icons. I am not aware of a way to address it, as it is local environment dependent.

**Comment by Tamhlacht** [comment] 2016-12-22 15:30
Hm, but it’s not - I just opened a tab with Google Maps and mouse-scrolled
and it moved leisurely outwards. Opened another tab with Brouter and when I
moused it behaved like a Victorian spinster going eeek and leaping on a
chair when she sees a mouse!

How do you join the Google Group as a maillist, please?

**Comment by poutnikl** [comment] 2016-12-22 15:50
I have supposed you got the mouse behaviour experience may differ between various webpages, so you should not be surprised Google Maps and Brouter-web may behave differently.  But as I am not the author, I cannot change anything on it. I can only advice to use zooming icons instead.

You need to register at GG as the member of the group and the configure it to use the email gateway to receive and send the posts. You may want to create a dedicated Gmail account for this or similar cases, not to expose your eventual personal email.

**Comment by Tamhlacht** [comment] 2016-12-22 17:01
Thanks, I’ll do that.

No, the zooming icons don’t work, because they also increase or decrease
the size of the legend box.

**Comment by poutnikl** [comment] 2016-12-22 17:09
Hm, that is very strange, related probably to similar mobile browser issues. But just guessing.
( I suppose you do not confuse them with eventual browser feature to zoom a general page.)

**Comment by Tamhlacht** [comment] 2016-12-23 05:28
Oh, you’re right, the Brouter legend box’s + and - aren’t having any effect
on the legend box size only on the map size.

**Comment by bagage** [comment] 2018-01-31 20:42
Closing this since the initial issue is solved -- please open a new issue if there is any.

**Closed by bagage** 2018-01-31 20:42 UTC
